language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN="3ba3d3dfd00260a566483ea1d4232690e0b6125997a4904e61790b6bab5b38ba" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
